env: "local" # Окружение - local, dev или prod
workers: 1
delay: 2s
random_delay: 0s
manticore:
  - index: questions
  - index: questions_ext
entry_chan_buffer: 20
splitter:
  opt_chunk_size: 1800 # оптимальный размер фрагмента контента для поиска, на эти фрагменты будет разбит контент
  max_chunk_size: 3600 # максимальный размер фрагмента контента для поиска
parsers:
  # - url: https://xn----8sba0bbi0cdm.xn--p1ai/qa/question/view-50275
  - url: https://xn----8sba0bbi0cdm.xn--p1ai/qa/video
    current: true
    # pages: 13
    fetch_all: false
  # - url: https://xn----8sba0bbi0cdm.xn--p1ai/qa/video
  #   pages: 0
  # - url: https://xn----8sba0bbi0cdm.xn--p1ai/qa/video
  #   pages: 1
    # pages: 0 означает, что нужно обработать все страницы. отрицательное значение так же означает все старницы.
    # Если параметр и число не указаны, означает что нужно обработать только последнюю запись на странице, последний выпуск вопрос ответ.
    # положительное число означет сколько страниц надо обработать, например 2 означает обработать все записи на двух страницах
    # pages: -1
  # - url: https://xn----8sba0bbi0cdm.xn--p1ai/qa/question